### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by smashwilson** [rackerlabs/docs-developer-blog#129]
Enable a sitemap with [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap).

**Comment by ktbartholomew** [comment]
We probably need something more than jekyll-sitemap for this site (and for deconst sites in general) because not all of the site's content is in Jekyll. A Jekyll-generated sitemap would include all of the blog stuff, but completely miss all of the docs content.

The challenge is that the sitemap might need to be updated whenever _any_ of the content repos change, and the service generating the sitemaps would need to be aware of content mappings across the entire site.

Maybe the logic for actually building and submitting the sitemap lives in another service and the preparers ping it via webhook after they submit content?

**Comment by smashwilson** [comment]
Oh good grief, you're right, this is going to be lot more of a pain. It should be good enough for getcarina.com though.

> Maybe the logic for actually building and submitting the sitemap lives in another service and the preparers ping it via webhook after they submit content?

Maybe... it depends heavily on both the control repo and on the actual envelopes available in Cloud Files at any given time. I'll open a deconst issue for the general case.

**Comment by smashwilson** [comment]
Filed as deconst/deconst-docs#134.

**Comment by smashwilson** [comment]
Er, wrong link. Filed as deconst/deconst-docs#191 instead.

**Comment by catlook** [comment]
So, gentlemen, shall we just close this issue as a won't fix?

**Comment by catlook** [comment]
closing
